In [2]:
import numpy as np

In [3]:
# Numerical differentiation
# Forward diffearence
def diff_forward(f, x, h=0.1):
    return (f(x+h)-f(x))/h
# Backward difference
def diff_backward(f, x, h=0.1):
    return (f(x)-f(x-h))/h
# Central difference for f’(x):
def diff_central(f, x, h=0.1):
    return (f(x+h)-f(x-h))/(2*h)
# end of diff_central
# Central difference for f’’(x):
def diff2_central(f, x, h=0.1):
    return (f(x+h)-2*f(x)+f(x-h))/h**2

In [6]:
# Numerical example 1
x = np.pi/4;
df_exact = np.cos(x)
ddf_exact = -np.sin(x)
h = 0.1
f = np.sin
df = diff_forward(f, x, h)
print("Approximations to the first derivative")
print("Forward difference: df = {:12.8f}, Error = {:10.3e}".format(df, df_exact-df))
df = diff_backward(f, x, h)
print("Backward difference: df = {:12.8f}, Error = {:10.3e}".format(df, df_exact-df))
df = diff_central(f, x, h)
print("Central difference: df = {:12.8f}, Error = {:10.3e}".format(df, df_exact-df))
print("Approximation to the second derivative")
ddf = diff2_central(f, x, h)
print("Central difference: ddf= {:12.8f}, Error = {:10.3e}".format(ddf, ddf_exact-ddf))

Approximations to the first derivative
Forward difference: df =   0.67060297, Error =  3.650e-02
Backward difference: df =   0.74125475, Error = -3.415e-02
Central difference: df =   0.70592886, Error =  1.178e-03
Approximation to the second derivative
Central difference: ddf=  -0.70651772, Error = -5.891e-04


In [9]:
def tridiag(v, d, w, N):
    """
    Help function
    Returns a tridiagonal matrix A=tridiag(v, d, w) of dimension N x N.
    """
    e = np.ones(N) # array [1,1,...,1] of length N
    A = v*np.diag(e[1:],-1)+d*np.diag(e)+w*np.diag(e[1:],1)
    return A

In [10]:
# Example 1, BVP
# Define the equation
# u’’ + p*u’ + q*u = r(x) on the interval [a,b]
# Boundary condition: u(a)=ua and u(b)=ub
p = 2
q = -3
def r(x):
    return 9*x
a, b = 0, 1
ua, ub = 1, np.exp(-3)+2*np.exp(1)-5
# The exact solution (if known)
def u_eksakt(x):
    return np.exp(-3*x)+2*np.exp(x)-3*x-2
# Set up the discrete system
N = 4
# Number of intervals
# Start the discretization
h = (b-a)/N
# Stepsize
x = np.linspace(a, b, N+1)
# The gridpoints x_0=a, x_1=a+h, .... , x_N=b
# Make a draft of the A-matrix (first and last row have to be adjusted)
v = 1-0.5*h*p
# Subdiagonal
d = -2+h**2*q
# Diagonal
w = 1+0.5*h*p
# Superdiagonal
A = tridiag(v, d, w, N+1)
# Make a draft of the b-vector
b = h**2*r(x)

In [13]:
# Modify the first equation (left boundary)
A[0,0] = 1
A[0,1] = 0
b[0] = ua
# Modify the last equation (right boundary)
A[N,N] = 1
A[N,N-1] = 0
b[N] = ub
U = np.linalg.solve(A, b)
# Solve the equation

In [14]:
# Print the matrix A, the right hand side b the numerical and exact solution
print("A =\n", A)
print("\nb =\n ", b)
print("\nU =\n ", U)
print("\nu(x)=\n", u_eksakt(x))

A =
 [[ 1.      0.      0.      0.      0.    ]
 [ 0.75   -2.1875  1.25    0.      0.    ]
 [ 0.      0.75   -2.1875  1.25    0.    ]
 [ 0.      0.      0.75   -2.1875  1.25  ]
 [ 0.      0.      0.      0.      1.    ]]

b =
  [1.         0.140625   0.28125    0.421875   0.48635073]

U =
  [1.         0.29317568 0.02555744 0.09382011 0.48635073]

u(x)=
 [1.         0.29041739 0.0205727  0.08939926 0.48635073]


In [ ]:
# Plot the solution of the BVP
xe = np.linspace(0,1,101)
plot(x,U,’.-’)
plot(xe, u_eksakt(xe),’:’)
xlabel(’x’)
ylabel(’u’)
legend([’Numerical’,’Exact’])
title(’Solution of a two-point BVP’);